/* 
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccountCoinsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountCoinsResponseTests
    {
        // TODO uncomment below to declare an instance variable for AccountCoinsResponse
        //private AccountCoinsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountCoinsResponse
            //instance = new AccountCoinsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountCoinsResponse
        /// </summary>
        [Test]
        public void AccountCoinsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountCoinsResponse
            //Assert.IsInstanceOfType<AccountCoinsResponse> (instance, "variable 'instance' is a AccountCoinsResponse");
        }


        /// <summary>
        /// Test the property 'BlockIdentifier'
        /// </summary>
        [Test]
        public void BlockIdentifierTest()
        {
            // TODO unit test for the property 'BlockIdentifier'
        }
        /// <summary>
        /// Test the property 'Coins'
        /// </summary>
        [Test]
        public void CoinsTest()
        {
            // TODO unit test for the property 'Coins'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
