/* 
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BalanceExemption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BalanceExemptionTests
    {
        // TODO uncomment below to declare an instance variable for BalanceExemption
        //private BalanceExemption instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BalanceExemption
            //instance = new BalanceExemption();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BalanceExemption
        /// </summary>
        [Test]
        public void BalanceExemptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BalanceExemption
            //Assert.IsInstanceOfType<BalanceExemption> (instance, "variable 'instance' is a BalanceExemption");
        }


        /// <summary>
        /// Test the property 'SubAccountAddress'
        /// </summary>
        [Test]
        public void SubAccountAddressTest()
        {
            // TODO unit test for the property 'SubAccountAddress'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'ExemptionType'
        /// </summary>
        [Test]
        public void ExemptionTypeTest()
        {
            // TODO unit test for the property 'ExemptionType'
        }

    }

}
