/* 
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Block
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BlockTests
    {
        // TODO uncomment below to declare an instance variable for Block
        //private Block instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Block
            //instance = new Block();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Block
        /// </summary>
        [Test]
        public void BlockInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Block
            //Assert.IsInstanceOfType<Block> (instance, "variable 'instance' is a Block");
        }


        /// <summary>
        /// Test the property 'BlockIdentifier'
        /// </summary>
        [Test]
        public void BlockIdentifierTest()
        {
            // TODO unit test for the property 'BlockIdentifier'
        }
        /// <summary>
        /// Test the property 'ParentBlockIdentifier'
        /// </summary>
        [Test]
        public void ParentBlockIdentifierTest()
        {
            // TODO unit test for the property 'ParentBlockIdentifier'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Test]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
