/* 
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ConstructionMetadataRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConstructionMetadataRequestTests
    {
        // TODO uncomment below to declare an instance variable for ConstructionMetadataRequest
        //private ConstructionMetadataRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConstructionMetadataRequest
            //instance = new ConstructionMetadataRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConstructionMetadataRequest
        /// </summary>
        [Test]
        public void ConstructionMetadataRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConstructionMetadataRequest
            //Assert.IsInstanceOfType<ConstructionMetadataRequest> (instance, "variable 'instance' is a ConstructionMetadataRequest");
        }


        /// <summary>
        /// Test the property 'NetworkIdentifier'
        /// </summary>
        [Test]
        public void NetworkIdentifierTest()
        {
            // TODO unit test for the property 'NetworkIdentifier'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Test]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'PublicKeys'
        /// </summary>
        [Test]
        public void PublicKeysTest()
        {
            // TODO unit test for the property 'PublicKeys'
        }

    }

}
