/* 
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ConstructionParseRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConstructionParseRequestTests
    {
        // TODO uncomment below to declare an instance variable for ConstructionParseRequest
        //private ConstructionParseRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConstructionParseRequest
            //instance = new ConstructionParseRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConstructionParseRequest
        /// </summary>
        [Test]
        public void ConstructionParseRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConstructionParseRequest
            //Assert.IsInstanceOfType<ConstructionParseRequest> (instance, "variable 'instance' is a ConstructionParseRequest");
        }


        /// <summary>
        /// Test the property 'NetworkIdentifier'
        /// </summary>
        [Test]
        public void NetworkIdentifierTest()
        {
            // TODO unit test for the property 'NetworkIdentifier'
        }
        /// <summary>
        /// Test the property 'Signed'
        /// </summary>
        [Test]
        public void SignedTest()
        {
            // TODO unit test for the property 'Signed'
        }
        /// <summary>
        /// Test the property 'Transaction'
        /// </summary>
        [Test]
        public void TransactionTest()
        {
            // TODO unit test for the property 'Transaction'
        }

    }

}
