/* 
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NetworkRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NetworkRequestTests
    {
        // TODO uncomment below to declare an instance variable for NetworkRequest
        //private NetworkRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NetworkRequest
            //instance = new NetworkRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NetworkRequest
        /// </summary>
        [Test]
        public void NetworkRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NetworkRequest
            //Assert.IsInstanceOfType<NetworkRequest> (instance, "variable 'instance' is a NetworkRequest");
        }


        /// <summary>
        /// Test the property 'NetworkIdentifier'
        /// </summary>
        [Test]
        public void NetworkIdentifierTest()
        {
            // TODO unit test for the property 'NetworkIdentifier'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
