/* 
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NetworkOptionsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NetworkOptionsResponseTests
    {
        // TODO uncomment below to declare an instance variable for NetworkOptionsResponse
        //private NetworkOptionsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NetworkOptionsResponse
            //instance = new NetworkOptionsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NetworkOptionsResponse
        /// </summary>
        [Test]
        public void NetworkOptionsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NetworkOptionsResponse
            //Assert.IsInstanceOfType<NetworkOptionsResponse> (instance, "variable 'instance' is a NetworkOptionsResponse");
        }


        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Allow'
        /// </summary>
        [Test]
        public void AllowTest()
        {
            // TODO unit test for the property 'Allow'
        }

    }

}
