/* 
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NetworkIdentifier
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NetworkIdentifierTests
    {
        // TODO uncomment below to declare an instance variable for NetworkIdentifier
        //private NetworkIdentifier instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NetworkIdentifier
            //instance = new NetworkIdentifier();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NetworkIdentifier
        /// </summary>
        [Test]
        public void NetworkIdentifierInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NetworkIdentifier
            //Assert.IsInstanceOfType<NetworkIdentifier> (instance, "variable 'instance' is a NetworkIdentifier");
        }


        /// <summary>
        /// Test the property 'Blockchain'
        /// </summary>
        [Test]
        public void BlockchainTest()
        {
            // TODO unit test for the property 'Blockchain'
        }
        /// <summary>
        /// Test the property 'Network'
        /// </summary>
        [Test]
        public void NetworkTest()
        {
            // TODO unit test for the property 'Network'
        }
        /// <summary>
        /// Test the property 'SubNetworkIdentifier'
        /// </summary>
        [Test]
        public void SubNetworkIdentifierTest()
        {
            // TODO unit test for the property 'SubNetworkIdentifier'
        }

    }

}
