/* 
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Operation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OperationTests
    {
        // TODO uncomment below to declare an instance variable for Operation
        //private Operation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Operation
            //instance = new Operation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Operation
        /// </summary>
        [Test]
        public void OperationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Operation
            //Assert.IsInstanceOfType<Operation> (instance, "variable 'instance' is a Operation");
        }


        /// <summary>
        /// Test the property 'OperationIdentifier'
        /// </summary>
        [Test]
        public void OperationIdentifierTest()
        {
            // TODO unit test for the property 'OperationIdentifier'
        }
        /// <summary>
        /// Test the property 'RelatedOperations'
        /// </summary>
        [Test]
        public void RelatedOperationsTest()
        {
            // TODO unit test for the property 'RelatedOperations'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Test]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'CoinChange'
        /// </summary>
        [Test]
        public void CoinChangeTest()
        {
            // TODO unit test for the property 'CoinChange'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
