/* 
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Version
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VersionTests
    {
        // TODO uncomment below to declare an instance variable for Version
        //private Version instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Version
            //instance = new Version();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Version
        /// </summary>
        [Test]
        public void VersionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Version
            //Assert.IsInstanceOfType<Version> (instance, "variable 'instance' is a Version");
        }


        /// <summary>
        /// Test the property 'RosettaVersion'
        /// </summary>
        [Test]
        public void RosettaVersionTest()
        {
            // TODO unit test for the property 'RosettaVersion'
        }
        /// <summary>
        /// Test the property 'NodeVersion'
        /// </summary>
        [Test]
        public void NodeVersionTest()
        {
            // TODO unit test for the property 'NodeVersion'
        }
        /// <summary>
        /// Test the property 'MiddlewareVersion'
        /// </summary>
        [Test]
        public void MiddlewareVersionTest()
        {
            // TODO unit test for the property 'MiddlewareVersion'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
