/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class AccountApiController : ControllerBase
    { 
        /// <summary>
        /// Get an Account&#x27;s Balance
        /// </summary>
        /// <remarks>Get an array of all AccountBalances for an AccountIdentifier and the BlockIdentifier at which the balance lookup was performed. The BlockIdentifier must always be returned because some consumers of account balance data need to know specifically at which block the balance was calculated to compare balances they compute from operations with the balance returned by the node. It is important to note that making a balance request for an account without populating the SubAccountIdentifier should not result in the balance of all possible SubAccountIdentifiers being returned. Rather, it should result in the balance pertaining to no SubAccountIdentifiers being returned (sometimes called the liquid balance). To get all balances associated with an account, it may be necessary to perform multiple balance requests with unique AccountIdentifiers. It is also possible to perform a historical balance lookup (if the server supports it) by passing in an optional BlockIdentifier.</remarks>
        /// <param name="body"></param>
        /// <response code="200">Expected response to a valid request</response>
        /// <response code="500">unexpected error</response>
        [HttpPost]
        [Route("/account/balance")]
        [ValidateModelState]
        [SwaggerOperation("AccountBalance")]
        [SwaggerResponse(statusCode: 200, type: typeof(AccountBalanceResponse), description: "Expected response to a valid request")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "unexpected error")]
        public virtual IActionResult AccountBalance([FromBody]AccountBalanceRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AccountBalanceResponse));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(Error));
            string exampleJson = null;
            exampleJson = "{\n  \"balances\" : [ {\n    \"metadata\" : { },\n    \"currency\" : {\n      \"symbol\" : \"BTC\",\n      \"metadata\" : {\n        \"Issuer\" : \"Satoshi\"\n      },\n      \"decimals\" : 8\n    },\n    \"value\" : \"1238089899992\"\n  }, {\n    \"metadata\" : { },\n    \"currency\" : {\n      \"symbol\" : \"BTC\",\n      \"metadata\" : {\n        \"Issuer\" : \"Satoshi\"\n      },\n      \"decimals\" : 8\n    },\n    \"value\" : \"1238089899992\"\n  } ],\n  \"metadata\" : {\n    \"sequence_number\" : 23\n  },\n  \"block_identifier\" : {\n    \"index\" : 1123941,\n    \"hash\" : \"0x1f2cc6c5027d2f201a5453ad1119574d2aed23a392654742ac3c78783c071f85\"\n  }\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<AccountBalanceResponse>(exampleJson)
                        : default(AccountBalanceResponse);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Get an Account&#x27;s Unspent Coins
        /// </summary>
        /// <remarks>Get an array of all unspent coins for an AccountIdentifier and the BlockIdentifier at which the lookup was performed. If your implementation does not support coins (i.e. it is for an account-based blockchain), you do not need to implement this endpoint. If you implementation does support coins (i.e. it is fro a UTXO-based blockchain), you MUST also complete the &#x60;/account/balance&#x60; endpoint. It is important to note that making a coins request for an account without populating the SubAccountIdentifier should not result in the coins of all possible SubAccountIdentifiers being returned. Rather, it should result in the coins pertaining to no SubAccountIdentifiers being returned. To get all coins associated with an account, it may be necessary to perform multiple coin requests with unique AccountIdentifiers. Optionally, an implementation may choose to support updating an AccountIdentifier&#x27;s unspent coins based on the contents of the mempool. Note, using this functionality breaks any guarantee of idempotency.</remarks>
        /// <param name="body"></param>
        /// <response code="200">Expected response to a valid request</response>
        /// <response code="500">unexpected error</response>
        [HttpPost]
        [Route("/account/coins")]
        [ValidateModelState]
        [SwaggerOperation("AccountCoins")]
        [SwaggerResponse(statusCode: 200, type: typeof(AccountCoinsResponse), description: "Expected response to a valid request")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "unexpected error")]
        public virtual IActionResult AccountCoins([FromBody]AccountCoinsRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AccountCoinsResponse));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default(Error));
            string exampleJson = null;
            exampleJson = "{\n  \"metadata\" : {\n    \"sequence_number\" : 23\n  },\n  \"coins\" : [ {\n    \"amount\" : {\n      \"metadata\" : { },\n      \"currency\" : {\n        \"symbol\" : \"BTC\",\n        \"metadata\" : {\n          \"Issuer\" : \"Satoshi\"\n        },\n        \"decimals\" : 8\n      },\n      \"value\" : \"1238089899992\"\n    },\n    \"coin_identifier\" : {\n      \"identifier\" : \"0x2f23fd8cca835af21f3ac375bac601f97ead75f2e79143bdf71fe2c4be043e8f:1\"\n    }\n  }, {\n    \"amount\" : {\n      \"metadata\" : { },\n      \"currency\" : {\n        \"symbol\" : \"BTC\",\n        \"metadata\" : {\n          \"Issuer\" : \"Satoshi\"\n        },\n        \"decimals\" : 8\n      },\n      \"value\" : \"1238089899992\"\n    },\n    \"coin_identifier\" : {\n      \"identifier\" : \"0x2f23fd8cca835af21f3ac375bac601f97ead75f2e79143bdf71fe2c4be043e8f:1\"\n    }\n  } ],\n  \"block_identifier\" : {\n    \"index\" : 1123941,\n    \"hash\" : \"0x1f2cc6c5027d2f201a5453ad1119574d2aed23a392654742ac3c78783c071f85\"\n  }\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<AccountCoinsResponse>(exampleJson)
                        : default(AccountCoinsResponse);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
