/* 
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Allow specifies supported Operation status, Operation types, and all possible error statuses. This Allow object is used by clients to validate the correctness of a Rosetta Server implementation. It is expected that these clients will error if they receive some response that contains any of the above information that is not specified here.
    /// </summary>
    [DataContract]
        public partial class Allow :  IEquatable<Allow>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Allow" /> class.
        /// </summary>
        /// <param name="operationStatuses">All Operation.Status this implementation supports. Any status that is returned during parsing that is not listed here will cause client validation to error. (required).</param>
        /// <param name="operationTypes">All Operation.Type this implementation supports. Any type that is returned during parsing that is not listed here will cause client validation to error. (required).</param>
        /// <param name="errors">All Errors that this implementation could return. Any error that is returned during parsing that is not listed here will cause client validation to error. (required).</param>
        /// <param name="historicalBalanceLookup">Any Rosetta implementation that supports querying the balance of an account at any height in the past should set this to true. (required).</param>
        /// <param name="timestampStartIndex">If populated, &#x60;timestamp_start_index&#x60; indicates the first block index where block timestamps are considered valid (i.e. all blocks less than &#x60;timestamp_start_index&#x60; could have invalid timestamps). This is useful when the genesis block (or blocks) of a network have timestamp 0. If not populated, block timestamps are assumed to be valid for all available blocks..</param>
        /// <param name="callMethods">All methods that are supported by the /call endpoint. Communicating which parameters should be provided to /call is the responsibility of the implementer (this is en lieu of defining an entire type system and requiring the implementer to define that in Allow). (required).</param>
        /// <param name="balanceExemptions">BalanceExemptions is an array of BalanceExemption indicating which account balances could change without a corresponding Operation. BalanceExemptions should be used sparingly as they may introduce significant complexity for integrators that attempt to reconcile all account balance changes. If your implementation relies on any BalanceExemptions, you MUST implement historical balance lookup (the ability to query an account balance at any BlockIdentifier). (required).</param>
        /// <param name="mempoolCoins">Any Rosetta implementation that can update an AccountIdentifier&#x27;s unspent coins based on the contents of the mempool should populate this field as true. If false, requests to &#x60;/account/coins&#x60; that set &#x60;include_mempool&#x60; as true will be automatically rejected. (required).</param>
        public Allow(List<OperationStatus> operationStatuses = default(List<OperationStatus>), List<string> operationTypes = default(List<string>), List<Error> errors = default(List<Error>), bool? historicalBalanceLookup = default(bool?), long? timestampStartIndex = default(long?), List<string> callMethods = default(List<string>), List<BalanceExemption> balanceExemptions = default(List<BalanceExemption>), bool? mempoolCoins = default(bool?))
        {
            // to ensure "operationStatuses" is required (not null)
            if (operationStatuses == null)
            {
                throw new InvalidDataException("operationStatuses is a required property for Allow and cannot be null");
            }
            else
            {
                this.OperationStatuses = operationStatuses;
            }
            // to ensure "operationTypes" is required (not null)
            if (operationTypes == null)
            {
                throw new InvalidDataException("operationTypes is a required property for Allow and cannot be null");
            }
            else
            {
                this.OperationTypes = operationTypes;
            }
            // to ensure "errors" is required (not null)
            if (errors == null)
            {
                throw new InvalidDataException("errors is a required property for Allow and cannot be null");
            }
            else
            {
                this.Errors = errors;
            }
            // to ensure "historicalBalanceLookup" is required (not null)
            if (historicalBalanceLookup == null)
            {
                throw new InvalidDataException("historicalBalanceLookup is a required property for Allow and cannot be null");
            }
            else
            {
                this.HistoricalBalanceLookup = historicalBalanceLookup;
            }
            // to ensure "callMethods" is required (not null)
            if (callMethods == null)
            {
                throw new InvalidDataException("callMethods is a required property for Allow and cannot be null");
            }
            else
            {
                this.CallMethods = callMethods;
            }
            // to ensure "balanceExemptions" is required (not null)
            if (balanceExemptions == null)
            {
                throw new InvalidDataException("balanceExemptions is a required property for Allow and cannot be null");
            }
            else
            {
                this.BalanceExemptions = balanceExemptions;
            }
            // to ensure "mempoolCoins" is required (not null)
            if (mempoolCoins == null)
            {
                throw new InvalidDataException("mempoolCoins is a required property for Allow and cannot be null");
            }
            else
            {
                this.MempoolCoins = mempoolCoins;
            }
            this.TimestampStartIndex = timestampStartIndex;
        }
        
        /// <summary>
        /// All Operation.Status this implementation supports. Any status that is returned during parsing that is not listed here will cause client validation to error.
        /// </summary>
        /// <value>All Operation.Status this implementation supports. Any status that is returned during parsing that is not listed here will cause client validation to error.</value>
        [DataMember(Name="operation_statuses", EmitDefaultValue=false)]
        public List<OperationStatus> OperationStatuses { get; set; }

        /// <summary>
        /// All Operation.Type this implementation supports. Any type that is returned during parsing that is not listed here will cause client validation to error.
        /// </summary>
        /// <value>All Operation.Type this implementation supports. Any type that is returned during parsing that is not listed here will cause client validation to error.</value>
        [DataMember(Name="operation_types", EmitDefaultValue=false)]
        public List<string> OperationTypes { get; set; }

        /// <summary>
        /// All Errors that this implementation could return. Any error that is returned during parsing that is not listed here will cause client validation to error.
        /// </summary>
        /// <value>All Errors that this implementation could return. Any error that is returned during parsing that is not listed here will cause client validation to error.</value>
        [DataMember(Name="errors", EmitDefaultValue=false)]
        public List<Error> Errors { get; set; }

        /// <summary>
        /// Any Rosetta implementation that supports querying the balance of an account at any height in the past should set this to true.
        /// </summary>
        /// <value>Any Rosetta implementation that supports querying the balance of an account at any height in the past should set this to true.</value>
        [DataMember(Name="historical_balance_lookup", EmitDefaultValue=false)]
        public bool? HistoricalBalanceLookup { get; set; }

        /// <summary>
        /// If populated, &#x60;timestamp_start_index&#x60; indicates the first block index where block timestamps are considered valid (i.e. all blocks less than &#x60;timestamp_start_index&#x60; could have invalid timestamps). This is useful when the genesis block (or blocks) of a network have timestamp 0. If not populated, block timestamps are assumed to be valid for all available blocks.
        /// </summary>
        /// <value>If populated, &#x60;timestamp_start_index&#x60; indicates the first block index where block timestamps are considered valid (i.e. all blocks less than &#x60;timestamp_start_index&#x60; could have invalid timestamps). This is useful when the genesis block (or blocks) of a network have timestamp 0. If not populated, block timestamps are assumed to be valid for all available blocks.</value>
        [DataMember(Name="timestamp_start_index", EmitDefaultValue=false)]
        public long? TimestampStartIndex { get; set; }

        /// <summary>
        /// All methods that are supported by the /call endpoint. Communicating which parameters should be provided to /call is the responsibility of the implementer (this is en lieu of defining an entire type system and requiring the implementer to define that in Allow).
        /// </summary>
        /// <value>All methods that are supported by the /call endpoint. Communicating which parameters should be provided to /call is the responsibility of the implementer (this is en lieu of defining an entire type system and requiring the implementer to define that in Allow).</value>
        [DataMember(Name="call_methods", EmitDefaultValue=false)]
        public List<string> CallMethods { get; set; }

        /// <summary>
        /// BalanceExemptions is an array of BalanceExemption indicating which account balances could change without a corresponding Operation. BalanceExemptions should be used sparingly as they may introduce significant complexity for integrators that attempt to reconcile all account balance changes. If your implementation relies on any BalanceExemptions, you MUST implement historical balance lookup (the ability to query an account balance at any BlockIdentifier).
        /// </summary>
        /// <value>BalanceExemptions is an array of BalanceExemption indicating which account balances could change without a corresponding Operation. BalanceExemptions should be used sparingly as they may introduce significant complexity for integrators that attempt to reconcile all account balance changes. If your implementation relies on any BalanceExemptions, you MUST implement historical balance lookup (the ability to query an account balance at any BlockIdentifier).</value>
        [DataMember(Name="balance_exemptions", EmitDefaultValue=false)]
        public List<BalanceExemption> BalanceExemptions { get; set; }

        /// <summary>
        /// Any Rosetta implementation that can update an AccountIdentifier&#x27;s unspent coins based on the contents of the mempool should populate this field as true. If false, requests to &#x60;/account/coins&#x60; that set &#x60;include_mempool&#x60; as true will be automatically rejected.
        /// </summary>
        /// <value>Any Rosetta implementation that can update an AccountIdentifier&#x27;s unspent coins based on the contents of the mempool should populate this field as true. If false, requests to &#x60;/account/coins&#x60; that set &#x60;include_mempool&#x60; as true will be automatically rejected.</value>
        [DataMember(Name="mempool_coins", EmitDefaultValue=false)]
        public bool? MempoolCoins { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Allow {\n");
            sb.Append("  OperationStatuses: ").Append(OperationStatuses).Append("\n");
            sb.Append("  OperationTypes: ").Append(OperationTypes).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  HistoricalBalanceLookup: ").Append(HistoricalBalanceLookup).Append("\n");
            sb.Append("  TimestampStartIndex: ").Append(TimestampStartIndex).Append("\n");
            sb.Append("  CallMethods: ").Append(CallMethods).Append("\n");
            sb.Append("  BalanceExemptions: ").Append(BalanceExemptions).Append("\n");
            sb.Append("  MempoolCoins: ").Append(MempoolCoins).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Allow);
        }

        /// <summary>
        /// Returns true if Allow instances are equal
        /// </summary>
        /// <param name="input">Instance of Allow to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Allow input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OperationStatuses == input.OperationStatuses ||
                    this.OperationStatuses != null &&
                    input.OperationStatuses != null &&
                    this.OperationStatuses.SequenceEqual(input.OperationStatuses)
                ) && 
                (
                    this.OperationTypes == input.OperationTypes ||
                    this.OperationTypes != null &&
                    input.OperationTypes != null &&
                    this.OperationTypes.SequenceEqual(input.OperationTypes)
                ) && 
                (
                    this.Errors == input.Errors ||
                    this.Errors != null &&
                    input.Errors != null &&
                    this.Errors.SequenceEqual(input.Errors)
                ) && 
                (
                    this.HistoricalBalanceLookup == input.HistoricalBalanceLookup ||
                    (this.HistoricalBalanceLookup != null &&
                    this.HistoricalBalanceLookup.Equals(input.HistoricalBalanceLookup))
                ) && 
                (
                    this.TimestampStartIndex == input.TimestampStartIndex ||
                    (this.TimestampStartIndex != null &&
                    this.TimestampStartIndex.Equals(input.TimestampStartIndex))
                ) && 
                (
                    this.CallMethods == input.CallMethods ||
                    this.CallMethods != null &&
                    input.CallMethods != null &&
                    this.CallMethods.SequenceEqual(input.CallMethods)
                ) && 
                (
                    this.BalanceExemptions == input.BalanceExemptions ||
                    this.BalanceExemptions != null &&
                    input.BalanceExemptions != null &&
                    this.BalanceExemptions.SequenceEqual(input.BalanceExemptions)
                ) && 
                (
                    this.MempoolCoins == input.MempoolCoins ||
                    (this.MempoolCoins != null &&
                    this.MempoolCoins.Equals(input.MempoolCoins))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OperationStatuses != null)
                    hashCode = hashCode * 59 + this.OperationStatuses.GetHashCode();
                if (this.OperationTypes != null)
                    hashCode = hashCode * 59 + this.OperationTypes.GetHashCode();
                if (this.Errors != null)
                    hashCode = hashCode * 59 + this.Errors.GetHashCode();
                if (this.HistoricalBalanceLookup != null)
                    hashCode = hashCode * 59 + this.HistoricalBalanceLookup.GetHashCode();
                if (this.TimestampStartIndex != null)
                    hashCode = hashCode * 59 + this.TimestampStartIndex.GetHashCode();
                if (this.CallMethods != null)
                    hashCode = hashCode * 59 + this.CallMethods.GetHashCode();
                if (this.BalanceExemptions != null)
                    hashCode = hashCode * 59 + this.BalanceExemptions.GetHashCode();
                if (this.MempoolCoins != null)
                    hashCode = hashCode * 59 + this.MempoolCoins.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
