# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    OpenAPI spec version: 1.4.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BalanceExemption(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sub_account_address': 'str',
        'currency': 'Currency',
        'exemption_type': 'ExemptionType'
    }

    attribute_map = {
        'sub_account_address': 'sub_account_address',
        'currency': 'currency',
        'exemption_type': 'exemption_type'
    }

    def __init__(self, sub_account_address=None, currency=None, exemption_type=None):  # noqa: E501
        """BalanceExemption - a model defined in Swagger"""  # noqa: E501
        self._sub_account_address = None
        self._currency = None
        self._exemption_type = None
        self.discriminator = None
        if sub_account_address is not None:
            self.sub_account_address = sub_account_address
        if currency is not None:
            self.currency = currency
        if exemption_type is not None:
            self.exemption_type = exemption_type

    @property
    def sub_account_address(self):
        """Gets the sub_account_address of this BalanceExemption.  # noqa: E501

        SubAccountAddress is the SubAccountIdentifier.Address that the BalanceExemption applies to (regardless of the value of SubAccountIdentifier.Metadata).  # noqa: E501

        :return: The sub_account_address of this BalanceExemption.  # noqa: E501
        :rtype: str
        """
        return self._sub_account_address

    @sub_account_address.setter
    def sub_account_address(self, sub_account_address):
        """Sets the sub_account_address of this BalanceExemption.

        SubAccountAddress is the SubAccountIdentifier.Address that the BalanceExemption applies to (regardless of the value of SubAccountIdentifier.Metadata).  # noqa: E501

        :param sub_account_address: The sub_account_address of this BalanceExemption.  # noqa: E501
        :type: str
        """

        self._sub_account_address = sub_account_address

    @property
    def currency(self):
        """Gets the currency of this BalanceExemption.  # noqa: E501


        :return: The currency of this BalanceExemption.  # noqa: E501
        :rtype: Currency
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this BalanceExemption.


        :param currency: The currency of this BalanceExemption.  # noqa: E501
        :type: Currency
        """

        self._currency = currency

    @property
    def exemption_type(self):
        """Gets the exemption_type of this BalanceExemption.  # noqa: E501


        :return: The exemption_type of this BalanceExemption.  # noqa: E501
        :rtype: ExemptionType
        """
        return self._exemption_type

    @exemption_type.setter
    def exemption_type(self, exemption_type):
        """Sets the exemption_type of this BalanceExemption.


        :param exemption_type: The exemption_type of this BalanceExemption.  # noqa: E501
        :type: ExemptionType
        """

        self._exemption_type = exemption_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BalanceExemption, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BalanceExemption):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
