# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    OpenAPI spec version: 1.4.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConstructionDeriveResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'account_identifier': 'AccountIdentifier',
        'metadata': 'object'
    }

    attribute_map = {
        'address': 'address',
        'account_identifier': 'account_identifier',
        'metadata': 'metadata'
    }

    def __init__(self, address=None, account_identifier=None, metadata=None):  # noqa: E501
        """ConstructionDeriveResponse - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._account_identifier = None
        self._metadata = None
        self.discriminator = None
        if address is not None:
            self.address = address
        if account_identifier is not None:
            self.account_identifier = account_identifier
        if metadata is not None:
            self.metadata = metadata

    @property
    def address(self):
        """Gets the address of this ConstructionDeriveResponse.  # noqa: E501

        [DEPRECATED by `account_identifier` in `v1.4.4`] Address in network-specific format.  # noqa: E501

        :return: The address of this ConstructionDeriveResponse.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this ConstructionDeriveResponse.

        [DEPRECATED by `account_identifier` in `v1.4.4`] Address in network-specific format.  # noqa: E501

        :param address: The address of this ConstructionDeriveResponse.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def account_identifier(self):
        """Gets the account_identifier of this ConstructionDeriveResponse.  # noqa: E501


        :return: The account_identifier of this ConstructionDeriveResponse.  # noqa: E501
        :rtype: AccountIdentifier
        """
        return self._account_identifier

    @account_identifier.setter
    def account_identifier(self, account_identifier):
        """Sets the account_identifier of this ConstructionDeriveResponse.


        :param account_identifier: The account_identifier of this ConstructionDeriveResponse.  # noqa: E501
        :type: AccountIdentifier
        """

        self._account_identifier = account_identifier

    @property
    def metadata(self):
        """Gets the metadata of this ConstructionDeriveResponse.  # noqa: E501


        :return: The metadata of this ConstructionDeriveResponse.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this ConstructionDeriveResponse.


        :param metadata: The metadata of this ConstructionDeriveResponse.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConstructionDeriveResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConstructionDeriveResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
