# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    OpenAPI spec version: 1.4.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.call_api import CallApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCallApi(unittest.TestCase):
    """CallApi unit test stubs"""

    def setUp(self):
        self.api = CallApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_call(self):
        """Test case for call

        Make a Network-Specific Procedure Call  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
