# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    OpenAPI spec version: 1.4.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.account_api import AccountApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_balance(self):
        """Test case for account_balance

        Get an Account's Balance  # noqa: E501
        """
        pass

    def test_account_coins(self):
        """Test case for account_coins

        Get an Account's Unspent Coins  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
