# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    OpenAPI spec version: 1.4.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.block import Block  # noqa: E501
from swagger_client.rest import ApiException


class TestBlock(unittest.TestCase):
    """Block unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlock(self):
        """Test Block"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.block.Block()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
