# coding: utf-8

"""
    Rosetta

    Build Once. Integrate Your Blockchain Everywhere.  # noqa: E501

    OpenAPI spec version: 1.4.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.account_coins_request import AccountCoinsRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountCoinsRequest(unittest.TestCase):
    """AccountCoinsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountCoinsRequest(self):
        """Test AccountCoinsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.account_coins_request.AccountCoinsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
