# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.transaction import Transaction  # noqa: F401,E501
from swagger_server import util


class BlockTransactionResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, transaction: Transaction=None):  # noqa: E501
        """BlockTransactionResponse - a model defined in Swagger

        :param transaction: The transaction of this BlockTransactionResponse.  # noqa: E501
        :type transaction: Transaction
        """
        self.swagger_types = {
            'transaction': Transaction
        }

        self.attribute_map = {
            'transaction': 'transaction'
        }
        self._transaction = transaction

    @classmethod
    def from_dict(cls, dikt) -> 'BlockTransactionResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BlockTransactionResponse of this BlockTransactionResponse.  # noqa: E501
        :rtype: BlockTransactionResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def transaction(self) -> Transaction:
        """Gets the transaction of this BlockTransactionResponse.


        :return: The transaction of this BlockTransactionResponse.
        :rtype: Transaction
        """
        return self._transaction

    @transaction.setter
    def transaction(self, transaction: Transaction):
        """Sets the transaction of this BlockTransactionResponse.


        :param transaction: The transaction of this BlockTransactionResponse.
        :type transaction: Transaction
        """
        if transaction is None:
            raise ValueError("Invalid value for `transaction`, must not be `None`")  # noqa: E501

        self._transaction = transaction
