# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.network_identifier import NetworkIdentifier  # noqa: F401,E501
from swagger_server import util


class ConstructionHashRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, network_identifier: NetworkIdentifier=None, signed_transaction: str=None):  # noqa: E501
        """ConstructionHashRequest - a model defined in Swagger

        :param network_identifier: The network_identifier of this ConstructionHashRequest.  # noqa: E501
        :type network_identifier: NetworkIdentifier
        :param signed_transaction: The signed_transaction of this ConstructionHashRequest.  # noqa: E501
        :type signed_transaction: str
        """
        self.swagger_types = {
            'network_identifier': NetworkIdentifier,
            'signed_transaction': str
        }

        self.attribute_map = {
            'network_identifier': 'network_identifier',
            'signed_transaction': 'signed_transaction'
        }
        self._network_identifier = network_identifier
        self._signed_transaction = signed_transaction

    @classmethod
    def from_dict(cls, dikt) -> 'ConstructionHashRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConstructionHashRequest of this ConstructionHashRequest.  # noqa: E501
        :rtype: ConstructionHashRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def network_identifier(self) -> NetworkIdentifier:
        """Gets the network_identifier of this ConstructionHashRequest.


        :return: The network_identifier of this ConstructionHashRequest.
        :rtype: NetworkIdentifier
        """
        return self._network_identifier

    @network_identifier.setter
    def network_identifier(self, network_identifier: NetworkIdentifier):
        """Sets the network_identifier of this ConstructionHashRequest.


        :param network_identifier: The network_identifier of this ConstructionHashRequest.
        :type network_identifier: NetworkIdentifier
        """
        if network_identifier is None:
            raise ValueError("Invalid value for `network_identifier`, must not be `None`")  # noqa: E501

        self._network_identifier = network_identifier

    @property
    def signed_transaction(self) -> str:
        """Gets the signed_transaction of this ConstructionHashRequest.


        :return: The signed_transaction of this ConstructionHashRequest.
        :rtype: str
        """
        return self._signed_transaction

    @signed_transaction.setter
    def signed_transaction(self, signed_transaction: str):
        """Sets the signed_transaction of this ConstructionHashRequest.


        :param signed_transaction: The signed_transaction of this ConstructionHashRequest.
        :type signed_transaction: str
        """
        if signed_transaction is None:
            raise ValueError("Invalid value for `signed_transaction`, must not be `None`")  # noqa: E501

        self._signed_transaction = signed_transaction
