/* 
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NetworkApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class NetworkApiTests
    {
        private NetworkApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NetworkApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NetworkApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' NetworkApi
            //Assert.IsInstanceOfType(typeof(NetworkApi), instance, "instance is a NetworkApi");
        }

        /// <summary>
        /// Test NetworkList
        /// </summary>
        [Test]
        public void NetworkListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MetadataRequest body = null;
            //var response = instance.NetworkList(body);
            //Assert.IsInstanceOf<NetworkListResponse> (response, "response is NetworkListResponse");
        }
        /// <summary>
        /// Test NetworkOptions
        /// </summary>
        [Test]
        public void NetworkOptionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NetworkRequest body = null;
            //var response = instance.NetworkOptions(body);
            //Assert.IsInstanceOf<NetworkOptionsResponse> (response, "response is NetworkOptionsResponse");
        }
        /// <summary>
        /// Test NetworkStatus
        /// </summary>
        [Test]
        public void NetworkStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NetworkRequest body = null;
            //var response = instance.NetworkStatus(body);
            //Assert.IsInstanceOf<NetworkStatusResponse> (response, "response is NetworkStatusResponse");
        }
    }

}
