/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// An AccountBalanceResponse is returned on the /account/balance endpoint. If an account has a balance for each AccountIdentifier describing it (ex: an ERC-20 token balance on a few smart contracts), an account balance request must be made with each AccountIdentifier. The &#x60;coins&#x60; field was removed and replaced by by &#x60;/account/coins&#x60; in &#x60;v1.4.7&#x60;.
    /// </summary>
    [DataContract]
    public partial class AccountBalanceResponse : IEquatable<AccountBalanceResponse>
    { 
        /// <summary>
        /// Gets or Sets BlockIdentifier
        /// </summary>
        [Required]
        [DataMember(Name="block_identifier")]
        public BlockIdentifier BlockIdentifier { get; set; }

        /// <summary>
        /// A single account may have a balance in multiple currencies.
        /// </summary>
        /// <value>A single account may have a balance in multiple currencies.</value>
        [Required]
        [DataMember(Name="balances")]
        public List<Amount> Balances { get; set; }

        /// <summary>
        /// Account-based blockchains that utilize a nonce or sequence number should include that number in the metadata. This number could be unique to the identifier or global across the account address.
        /// </summary>
        /// <value>Account-based blockchains that utilize a nonce or sequence number should include that number in the metadata. This number could be unique to the identifier or global across the account address.</value>
        [DataMember(Name="metadata")]
        public Object Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AccountBalanceResponse {\n");
            sb.Append("  BlockIdentifier: ").Append(BlockIdentifier).Append("\n");
            sb.Append("  Balances: ").Append(Balances).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AccountBalanceResponse)obj);
        }

        /// <summary>
        /// Returns true if AccountBalanceResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of AccountBalanceResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AccountBalanceResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    BlockIdentifier == other.BlockIdentifier ||
                    BlockIdentifier != null &&
                    BlockIdentifier.Equals(other.BlockIdentifier)
                ) && 
                (
                    Balances == other.Balances ||
                    Balances != null &&
                    Balances.SequenceEqual(other.Balances)
                ) && 
                (
                    Metadata == other.Metadata ||
                    Metadata != null &&
                    Metadata.Equals(other.Metadata)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (BlockIdentifier != null)
                    hashCode = hashCode * 59 + BlockIdentifier.GetHashCode();
                    if (Balances != null)
                    hashCode = hashCode * 59 + Balances.GetHashCode();
                    if (Metadata != null)
                    hashCode = hashCode * 59 + Metadata.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AccountBalanceResponse left, AccountBalanceResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AccountBalanceResponse left, AccountBalanceResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
