/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// BlockEventType determines if a BlockEvent represents the addition or removal of a block.
        /// </summary>
        /// <value>BlockEventType determines if a BlockEvent represents the addition or removal of a block.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum BlockEventType
        {
            /// <summary>
            /// Enum AddedEnum for block_added
            /// </summary>
            [EnumMember(Value = "block_added")]
            AddedEnum = 0,
            /// <summary>
            /// Enum RemovedEnum for block_removed
            /// </summary>
            [EnumMember(Value = "block_removed")]
            RemovedEnum = 1        }
}
