/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// CallResponse contains the result of a &#x60;/call&#x60; invocation.
    /// </summary>
    [DataContract]
    public partial class CallResponse : IEquatable<CallResponse>
    { 
        /// <summary>
        /// Result contains the result of the &#x60;/call&#x60; invocation. This result will not be inspected or interpreted by Rosetta tooling and is left to the caller to decode.
        /// </summary>
        /// <value>Result contains the result of the &#x60;/call&#x60; invocation. This result will not be inspected or interpreted by Rosetta tooling and is left to the caller to decode.</value>
        [Required]
        [DataMember(Name="result")]
        public Object Result { get; set; }

        /// <summary>
        /// Idempotent indicates that if &#x60;/call&#x60; is invoked with the same CallRequest again, at any point in time, it will return the same CallResponse. Integrators may cache the CallResponse if this is set to true to avoid making unnecessary calls to the Rosetta implementation. For this reason, implementers should be very conservative about returning true here or they could cause issues for the caller.
        /// </summary>
        /// <value>Idempotent indicates that if &#x60;/call&#x60; is invoked with the same CallRequest again, at any point in time, it will return the same CallResponse. Integrators may cache the CallResponse if this is set to true to avoid making unnecessary calls to the Rosetta implementation. For this reason, implementers should be very conservative about returning true here or they could cause issues for the caller.</value>
        [Required]
        [DataMember(Name="idempotent")]
        public bool? Idempotent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CallResponse {\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  Idempotent: ").Append(Idempotent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CallResponse)obj);
        }

        /// <summary>
        /// Returns true if CallResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of CallResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CallResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Result == other.Result ||
                    Result != null &&
                    Result.Equals(other.Result)
                ) && 
                (
                    Idempotent == other.Idempotent ||
                    Idempotent != null &&
                    Idempotent.Equals(other.Idempotent)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Result != null)
                    hashCode = hashCode * 59 + Result.GetHashCode();
                    if (Idempotent != null)
                    hashCode = hashCode * 59 + Idempotent.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CallResponse left, CallResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CallResponse left, CallResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
