/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * OpenAPI spec version: 1.4.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// SyncStatus is used to provide additional context about an implementation&#x27;s sync status. This object is often used by implementations to indicate healthiness when block data cannot be queried until some sync phase completes or cannot be determined by comparing the timestamp of the most recent block with the current time.
    /// </summary>
    [DataContract]
    public partial class SyncStatus : IEquatable<SyncStatus>
    { 
        /// <summary>
        /// CurrentIndex is the index of the last synced block in the current stage. This is a separate field from current_block_identifier in NetworkStatusResponse because blocks with indices up to and including the current_index may not yet be queryable by the caller. To reiterate, all indices up to and including current_block_identifier in NetworkStatusResponse must be queryable via the /block endpoint (excluding indices less than oldest_block_identifier).
        /// </summary>
        /// <value>CurrentIndex is the index of the last synced block in the current stage. This is a separate field from current_block_identifier in NetworkStatusResponse because blocks with indices up to and including the current_index may not yet be queryable by the caller. To reiterate, all indices up to and including current_block_identifier in NetworkStatusResponse must be queryable via the /block endpoint (excluding indices less than oldest_block_identifier).</value>
        [DataMember(Name="current_index")]
        public long? CurrentIndex { get; set; }

        /// <summary>
        /// TargetIndex is the index of the block that the implementation is attempting to sync to in the current stage.
        /// </summary>
        /// <value>TargetIndex is the index of the block that the implementation is attempting to sync to in the current stage.</value>
        [DataMember(Name="target_index")]
        public long? TargetIndex { get; set; }

        /// <summary>
        /// Stage is the phase of the sync process.
        /// </summary>
        /// <value>Stage is the phase of the sync process.</value>
        [DataMember(Name="stage")]
        public string Stage { get; set; }

        /// <summary>
        /// sycned is a boolean that indicates if an implementation has synced up to the most recent block. If this field is not populated, the caller should rely on a traditional tip timestamp comparison to determine if an implementation is synced. This field is particularly useful for quiescent blockchains (blocks only produced when there are pending transactions). In these blockchains, the most recent block could have a timestamp far behind the current time but the node could be healthy and at tip.
        /// </summary>
        /// <value>sycned is a boolean that indicates if an implementation has synced up to the most recent block. If this field is not populated, the caller should rely on a traditional tip timestamp comparison to determine if an implementation is synced. This field is particularly useful for quiescent blockchains (blocks only produced when there are pending transactions). In these blockchains, the most recent block could have a timestamp far behind the current time but the node could be healthy and at tip.</value>
        [DataMember(Name="synced")]
        public bool? Synced { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SyncStatus {\n");
            sb.Append("  CurrentIndex: ").Append(CurrentIndex).Append("\n");
            sb.Append("  TargetIndex: ").Append(TargetIndex).Append("\n");
            sb.Append("  Stage: ").Append(Stage).Append("\n");
            sb.Append("  Synced: ").Append(Synced).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SyncStatus)obj);
        }

        /// <summary>
        /// Returns true if SyncStatus instances are equal
        /// </summary>
        /// <param name="other">Instance of SyncStatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SyncStatus other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CurrentIndex == other.CurrentIndex ||
                    CurrentIndex != null &&
                    CurrentIndex.Equals(other.CurrentIndex)
                ) && 
                (
                    TargetIndex == other.TargetIndex ||
                    TargetIndex != null &&
                    TargetIndex.Equals(other.TargetIndex)
                ) && 
                (
                    Stage == other.Stage ||
                    Stage != null &&
                    Stage.Equals(other.Stage)
                ) && 
                (
                    Synced == other.Synced ||
                    Synced != null &&
                    Synced.Equals(other.Synced)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CurrentIndex != null)
                    hashCode = hashCode * 59 + CurrentIndex.GetHashCode();
                    if (TargetIndex != null)
                    hashCode = hashCode * 59 + TargetIndex.GetHashCode();
                    if (Stage != null)
                    hashCode = hashCode * 59 + Stage.GetHashCode();
                    if (Synced != null)
                    hashCode = hashCode * 59 + Synced.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SyncStatus left, SyncStatus right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SyncStatus left, SyncStatus right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
